dist: xenial
sudo: required
language: go
go:
  - 1.12.x
services:
  - mysql
env:
  matrix:
    - JOB=go-test
    - JOB=bazel-test
    - JOB=bazel-build
before_install:
  - 'if [[ "${JOB}" = bazel-* ]]; then hack/install-bazel.sh; fi'
before_script:
  - 'if [[ "${JOB}" == *-test ]]; then mysql -e "CREATE DATABASE IF NOT EXISTS publr_test"; fi'
script:
  - 'if [ "${JOB}" = "go-test" ]; then go test -race -v -covermode=atomic -coverprofile=coverage.txt ./...; fi'
  - 'if [ "${JOB}" = "bazel-test" ]; then bazel test --test_output=errors //...; fi'
  - 'if [ "${JOB}" = "bazel-build" ]; then bazel build //...; fi'
after_success:
  - 'if [ "${JOB}" = "go-test" ]; then bash <(curl -s https://codecov.io/bash); fi'