version: '3.7'
services:
  http-proxy:
    image: publr/http-proxy:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    command: [
      "--insecure-server", "true"
    ]
    networks:
      - default
    ports:
      - 8000:8000
  posts:
    image: publr/posts:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    command: [
      "--service-name", "posts",
      "--server-address", ":9000",
      "--database-host", "database",
      "--database-user", "publr",
      "--database-password", "secret",
      "--database-name", "publr"
    ]
    networks:
      - default
  sites:
    image: publr/sites:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    command: [
      "--service-name", "sites",
      "--server-address", ":9000",
      "--database-host", "database",
      "--database-user", "publr",
      "--database-password", "secret",
      "--database-name", "publr"
    ]
    networks:
      - default
  users:
    image: publr/users:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    command: [
      "--service-name", "users",
      "--server-address", ":9000",
      "--database-host", "database",
      "--database-user", "publr",
      "--database-password", "secret",
      "--database-name", "publr"
    ]
    networks:
      - default
  database:
    image: mysql:8.0
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - ./data/schema:/docker-entrypoint-initdb.d
      - database_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_DATABASE: publr
      MYSQL_USER: publr
      MYSQL_PASSWORD: secret
      TZ: Asia/Jakarta
    networks:
      - default
volumes:
  database_data:
networks:
  default: