apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: publr-cert
spec:
  request: $(cat config/certs/server.csr | base64 | tr -d '\n')
  usages:
  - digital signature
  - key encipherment
  - server auth