apiVersion: v1
kind: Secret
metadata:
  name: publr-tls
type: kubernetes.io/tls
data:
  tls.crt: $(cat config/certs/server.crt | base64 | tr -d '\n')
  tls.key: $(cat config/certs/server-key.pem | base64 | tr -d '\n')