// Copyright 2019 Publr Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/service/server/users/datastore/datastore.go

// Package mock_datastore is a generated GoMock package.
package mock_datastore

import (
	gomock "github.com/golang/mock/gomock"
	v1alpha2 "github.com/prksu/publr/pkg/api/users/v1alpha2"
	reflect "reflect"
)

// MockUserDatastore is a mock of UserDatastore interface
type MockUserDatastore struct {
	ctrl     *gomock.Controller
	recorder *MockUserDatastoreMockRecorder
}

// MockUserDatastoreMockRecorder is the mock recorder for MockUserDatastore
type MockUserDatastoreMockRecorder struct {
	mock *MockUserDatastore
}

// NewMockUserDatastore creates a new mock instance
func NewMockUserDatastore(ctrl *gomock.Controller) *MockUserDatastore {
	mock := &MockUserDatastore{ctrl: ctrl}
	mock.recorder = &MockUserDatastoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockUserDatastore) EXPECT() *MockUserDatastoreMockRecorder {
	return m.recorder
}

// List mocks base method
func (m *MockUserDatastore) List(sitedomain string, start, offset int) ([]*v1alpha2.User, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", sitedomain, start, offset)
	ret0, _ := ret[0].([]*v1alpha2.User)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List
func (mr *MockUserDatastoreMockRecorder) List(sitedomain, start, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockUserDatastore)(nil).List), sitedomain, start, offset)
}

// Create mocks base method
func (m *MockUserDatastore) Create(sitedomain string, user *v1alpha2.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", sitedomain, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create
func (mr *MockUserDatastoreMockRecorder) Create(sitedomain, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserDatastore)(nil).Create), sitedomain, user)
}

// Get mocks base method
func (m *MockUserDatastore) Get(sitedomain, username string) (*v1alpha2.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", sitedomain, username)
	ret0, _ := ret[0].(*v1alpha2.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get
func (mr *MockUserDatastoreMockRecorder) Get(sitedomain, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockUserDatastore)(nil).Get), sitedomain, username)
}

// Update mocks base method
func (m *MockUserDatastore) Update(sitedomain, username string, user *v1alpha2.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", sitedomain, username, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update
func (mr *MockUserDatastoreMockRecorder) Update(sitedomain, username, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserDatastore)(nil).Update), sitedomain, username, user)
}

// Delete mocks base method
func (m *MockUserDatastore) Delete(sitedomain, username string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", sitedomain, username)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockUserDatastoreMockRecorder) Delete(sitedomain, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserDatastore)(nil).Delete), sitedomain, username)
}

// Search mocks base method
func (m *MockUserDatastore) Search(query string) ([]*v1alpha2.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", query)
	ret0, _ := ret[0].([]*v1alpha2.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search
func (mr *MockUserDatastoreMockRecorder) Search(query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockUserDatastore)(nil).Search), query)
}
