// Copyright 2019 Publr Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/users/v1alpha2/users.proto

package users

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User_UserRoles int32

const (
	User_READER        User_UserRoles = 0
	User_AUTHOR        User_UserRoles = 1
	User_ADMINISTRATOR User_UserRoles = 2
	User_OWNER         User_UserRoles = 3
)

var User_UserRoles_name = map[int32]string{
	0: "READER",
	1: "AUTHOR",
	2: "ADMINISTRATOR",
	3: "OWNER",
}

var User_UserRoles_value = map[string]int32{
	"READER":        0,
	"AUTHOR":        1,
	"ADMINISTRATOR": 2,
	"OWNER":         3,
}

func (x User_UserRoles) String() string {
	return proto.EnumName(User_UserRoles_name, int32(x))
}

func (User_UserRoles) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1eadd090641503e8, []int{0, 0}
}

type User struct {
	Name                 string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email                string               `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password             string               `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Username             string               `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Fullname             string               `protobuf:"bytes,5,opt,name=fullname,proto3" json:"fullname,omitempty"`
	Role                 User_UserRoles       `protobuf:"varint,6,opt,name=role,proto3,enum=publr.users.v1alpha2.User_UserRoles" json:"role,omitempty"`
	CreateTime           *timestamp.Timestamp `protobuf:"bytes,7,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime           *timestamp.Timestamp `protobuf:"bytes,8,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_1eadd090641503e8, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetFullname() string {
	if m != nil {
		return m.Fullname
	}
	return ""
}

func (m *User) GetRole() User_UserRoles {
	if m != nil {
		return m.Role
	}
	return User_READER
}

func (m *User) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *User) GetUpdateTime() *timestamp.Timestamp {
	if m != nil {
		return m.UpdateTime
	}
	return nil
}

type UserList struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	NextPageToken        string   `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserList) Reset()         { *m = UserList{} }
func (m *UserList) String() string { return proto.CompactTextString(m) }
func (*UserList) ProtoMessage()    {}
func (*UserList) Descriptor() ([]byte, []int) {
	return fileDescriptor_1eadd090641503e8, []int{1}
}

func (m *UserList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserList.Unmarshal(m, b)
}
func (m *UserList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserList.Marshal(b, m, deterministic)
}
func (m *UserList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserList.Merge(m, src)
}
func (m *UserList) XXX_Size() int {
	return xxx_messageInfo_UserList.Size(m)
}
func (m *UserList) XXX_DiscardUnknown() {
	xxx_messageInfo_UserList.DiscardUnknown(m)
}

var xxx_messageInfo_UserList proto.InternalMessageInfo

func (m *UserList) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *UserList) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

type ListUserRequest struct {
	Parent               string   `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	OrderBy              string   `protobuf:"bytes,2,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	PageSize             int32    `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken            string   `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUserRequest) Reset()         { *m = ListUserRequest{} }
func (m *ListUserRequest) String() string { return proto.CompactTextString(m) }
func (*ListUserRequest) ProtoMessage()    {}
func (*ListUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1eadd090641503e8, []int{2}
}

func (m *ListUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUserRequest.Unmarshal(m, b)
}
func (m *ListUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUserRequest.Marshal(b, m, deterministic)
}
func (m *ListUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUserRequest.Merge(m, src)
}
func (m *ListUserRequest) XXX_Size() int {
	return xxx_messageInfo_ListUserRequest.Size(m)
}
func (m *ListUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListUserRequest proto.InternalMessageInfo

func (m *ListUserRequest) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *ListUserRequest) GetOrderBy() string {
	if m != nil {
		return m.OrderBy
	}
	return ""
}

func (m *ListUserRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListUserRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

type CreateUserRequest struct {
	Parent               string   `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	User                 *User    `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1eadd090641503e8, []int{3}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *CreateUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type GetUserRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1eadd090641503e8, []int{4}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UpdateUserRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	User                 *User    `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1eadd090641503e8, []int{5}
}

func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(m, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type DeleteUserRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserRequest) Reset()         { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()    {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1eadd090641503e8, []int{6}
}

func (m *DeleteUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserRequest.Unmarshal(m, b)
}
func (m *DeleteUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserRequest.Marshal(b, m, deterministic)
}
func (m *DeleteUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserRequest.Merge(m, src)
}
func (m *DeleteUserRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUserRequest.Size(m)
}
func (m *DeleteUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserRequest proto.InternalMessageInfo

func (m *DeleteUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type SearchUserRequest struct {
	Parent               string   `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	Query                string   `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	OrderBy              string   `protobuf:"bytes,3,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	PageSize             int32    `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken            string   `protobuf:"bytes,5,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchUserRequest) Reset()         { *m = SearchUserRequest{} }
func (m *SearchUserRequest) String() string { return proto.CompactTextString(m) }
func (*SearchUserRequest) ProtoMessage()    {}
func (*SearchUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1eadd090641503e8, []int{7}
}

func (m *SearchUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchUserRequest.Unmarshal(m, b)
}
func (m *SearchUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchUserRequest.Marshal(b, m, deterministic)
}
func (m *SearchUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchUserRequest.Merge(m, src)
}
func (m *SearchUserRequest) XXX_Size() int {
	return xxx_messageInfo_SearchUserRequest.Size(m)
}
func (m *SearchUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchUserRequest proto.InternalMessageInfo

func (m *SearchUserRequest) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *SearchUserRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *SearchUserRequest) GetOrderBy() string {
	if m != nil {
		return m.OrderBy
	}
	return ""
}

func (m *SearchUserRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *SearchUserRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

func init() {
	proto.RegisterEnum("publr.users.v1alpha2.User_UserRoles", User_UserRoles_name, User_UserRoles_value)
	proto.RegisterType((*User)(nil), "publr.users.v1alpha2.User")
	proto.RegisterType((*UserList)(nil), "publr.users.v1alpha2.UserList")
	proto.RegisterType((*ListUserRequest)(nil), "publr.users.v1alpha2.ListUserRequest")
	proto.RegisterType((*CreateUserRequest)(nil), "publr.users.v1alpha2.CreateUserRequest")
	proto.RegisterType((*GetUserRequest)(nil), "publr.users.v1alpha2.GetUserRequest")
	proto.RegisterType((*UpdateUserRequest)(nil), "publr.users.v1alpha2.UpdateUserRequest")
	proto.RegisterType((*DeleteUserRequest)(nil), "publr.users.v1alpha2.DeleteUserRequest")
	proto.RegisterType((*SearchUserRequest)(nil), "publr.users.v1alpha2.SearchUserRequest")
}

func init() { proto.RegisterFile("api/users/v1alpha2/users.proto", fileDescriptor_1eadd090641503e8) }

var fileDescriptor_1eadd090641503e8 = []byte{
	// 748 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0x5d, 0x4f, 0x13, 0x4d,
	0x14, 0x7e, 0xb7, 0x5f, 0xb4, 0x87, 0x00, 0xed, 0x84, 0x90, 0xbe, 0xe5, 0x7d, 0xb1, 0xd9, 0xa0,
	0x54, 0x2e, 0x76, 0xb5, 0xc4, 0xc4, 0x48, 0xbc, 0x28, 0xd2, 0x28, 0x89, 0x82, 0xd9, 0x96, 0x90,
	0xe8, 0x45, 0xb3, 0x6d, 0x0f, 0x65, 0xc3, 0xb6, 0xbb, 0xcc, 0xcc, 0x82, 0x40, 0x48, 0xd4, 0x0b,
	0x6f, 0xbc, 0xf4, 0xc6, 0xff, 0xe5, 0x5f, 0xf0, 0x5f, 0x78, 0x63, 0x66, 0x66, 0x97, 0x0a, 0xfd,
	0x58, 0xbc, 0x69, 0x7a, 0xe6, 0x7c, 0x3e, 0xe7, 0x79, 0x76, 0x06, 0x56, 0x6c, 0xdf, 0x31, 0x03,
	0x86, 0x94, 0x99, 0xa7, 0x8f, 0x6d, 0xd7, 0x3f, 0xb2, 0xab, 0xca, 0x34, 0x7c, 0xea, 0x71, 0x8f,
	0x2c, 0xfa, 0x41, 0xdb, 0xa5, 0x86, 0x3a, 0x8a, 0x22, 0x4a, 0xff, 0xf5, 0x3c, 0xaf, 0xe7, 0xa2,
	0x29, 0x92, 0xed, 0xc1, 0xc0, 0xe3, 0x36, 0x77, 0xbc, 0x41, 0x98, 0x53, 0x5a, 0x0e, 0xbd, 0xd2,
	0x6a, 0x07, 0x87, 0x26, 0xf6, 0x7d, 0x7e, 0x1e, 0x3a, 0xef, 0xdd, 0x76, 0x72, 0xa7, 0x8f, 0x8c,
	0xdb, 0x7d, 0x5f, 0x05, 0xe8, 0xbf, 0x12, 0x90, 0xda, 0x67, 0x48, 0x09, 0x81, 0xd4, 0xc0, 0xee,
	0x63, 0x51, 0x2b, 0x6b, 0x95, 0x9c, 0x25, 0xff, 0x93, 0x45, 0x48, 0x63, 0xdf, 0x76, 0xdc, 0x62,
	0x42, 0x1e, 0x2a, 0x83, 0x94, 0x20, 0xeb, 0xdb, 0x8c, 0x9d, 0x79, 0xb4, 0x5b, 0x4c, 0x4a, 0xc7,
	0xb5, 0x2d, 0x7c, 0x62, 0x78, 0x59, 0x29, 0xa5, 0x7c, 0x91, 0x2d, 0x7c, 0x87, 0x81, 0xeb, 0x4a,
	0x5f, 0x5a, 0xf9, 0x22, 0x9b, 0x3c, 0x85, 0x14, 0xf5, 0x5c, 0x2c, 0x66, 0xca, 0x5a, 0x65, 0xbe,
	0xba, 0x6a, 0x8c, 0xdb, 0x83, 0x21, 0xe6, 0x94, 0x3f, 0x96, 0xe7, 0x22, 0xb3, 0x64, 0x06, 0xd9,
	0x84, 0xd9, 0x0e, 0x45, 0x9b, 0x63, 0x4b, 0x40, 0x2b, 0xce, 0x94, 0xb5, 0xca, 0x6c, 0xb5, 0x64,
	0x28, 0xdc, 0x46, 0x84, 0xdb, 0x68, 0x46, 0xb8, 0x2d, 0x50, 0xe1, 0xe2, 0x40, 0x24, 0x07, 0x7e,
	0xf7, 0x3a, 0x39, 0x1b, 0x9f, 0xac, 0xc2, 0xc5, 0x81, 0x5e, 0x83, 0xdc, 0xf5, 0x30, 0x04, 0x20,
	0x63, 0xd5, 0x6b, 0xdb, 0x75, 0x2b, 0xff, 0x8f, 0xf8, 0x5f, 0xdb, 0x6f, 0xbe, 0xda, 0xb3, 0xf2,
	0x1a, 0x29, 0xc0, 0x5c, 0x6d, 0xfb, 0xcd, 0xce, 0xee, 0x4e, 0xa3, 0x69, 0xd5, 0x9a, 0x7b, 0x56,
	0x3e, 0x41, 0x72, 0x90, 0xde, 0x3b, 0xd8, 0xad, 0x5b, 0xf9, 0xa4, 0xde, 0x85, 0xac, 0x28, 0xf1,
	0xda, 0x61, 0x9c, 0x3c, 0x82, 0xb4, 0xc4, 0x5b, 0xd4, 0xca, 0x49, 0x39, 0xc5, 0xc4, 0x1d, 0x58,
	0x2a, 0x90, 0x3c, 0x80, 0x85, 0x01, 0x7e, 0xe0, 0x2d, 0xdf, 0xee, 0x61, 0x8b, 0x7b, 0xc7, 0x38,
	0x08, 0x89, 0x9a, 0x13, 0xc7, 0x6f, 0xed, 0x1e, 0x36, 0xc5, 0xa1, 0xfe, 0x51, 0x83, 0x05, 0xd1,
	0x42, 0xe6, 0xe2, 0x49, 0x80, 0x8c, 0x93, 0x25, 0xc8, 0xf8, 0x36, 0xc5, 0x01, 0x0f, 0x09, 0x0f,
	0x2d, 0xf2, 0x2f, 0x64, 0x3d, 0xda, 0x45, 0xda, 0x6a, 0x9f, 0x87, 0xc5, 0x66, 0xa4, 0xbd, 0x75,
	0x4e, 0x96, 0x21, 0x27, 0x3b, 0x31, 0xe7, 0x02, 0x25, 0xf1, 0x69, 0x41, 0x7c, 0x0f, 0x1b, 0xce,
	0x05, 0x92, 0xff, 0x01, 0xfe, 0x18, 0x43, 0x51, 0x2f, 0xc3, 0xd5, 0x08, 0xef, 0xa1, 0xf0, 0x42,
	0xae, 0xfd, 0x2e, 0x33, 0x18, 0x90, 0x12, 0x00, 0x65, 0xff, 0xe9, 0x8b, 0x90, 0x71, 0xfa, 0x2a,
	0xcc, 0xbf, 0xc4, 0x1b, 0xe8, 0xc6, 0x88, 0x59, 0x3f, 0x80, 0xc2, 0xbe, 0x24, 0x2f, 0x26, 0xf0,
	0xaf, 0xdb, 0xaf, 0x41, 0x61, 0x1b, 0x5d, 0x8c, 0x2d, 0xac, 0x7f, 0xd7, 0xa0, 0xd0, 0x40, 0x9b,
	0x76, 0x8e, 0xee, 0xb2, 0x85, 0x45, 0x48, 0x9f, 0x04, 0x48, 0x23, 0x1a, 0x94, 0x71, 0x83, 0x9f,
	0xe4, 0x14, 0x7e, 0x52, 0x53, 0xf9, 0x49, 0xdf, 0xe2, 0xa7, 0xfa, 0x35, 0x03, 0xb3, 0x62, 0xa8,
	0x06, 0xd2, 0x53, 0xa7, 0x83, 0xe4, 0x12, 0xb2, 0x91, 0x62, 0xc8, 0xfd, 0xf1, 0x1b, 0xb8, 0xa5,
	0xa8, 0xd2, 0xca, 0xe4, 0x45, 0x89, 0x50, 0xbd, 0xf2, 0xf9, 0xc7, 0xcf, 0x6f, 0x09, 0x9d, 0x94,
	0x87, 0x57, 0xdf, 0xa5, 0x82, 0xfa, 0x9c, 0x39, 0x1c, 0x99, 0xb9, 0x7e, 0xa5, 0xee, 0x42, 0xf2,
	0x49, 0x03, 0x18, 0xaa, 0x85, 0xac, 0x8d, 0x2f, 0x3c, 0xa2, 0xa7, 0xd2, 0x14, 0xaa, 0x74, 0x43,
	0x76, 0xaf, 0xe8, 0xb1, 0xdd, 0x9f, 0x49, 0x52, 0x49, 0x00, 0x33, 0xa1, 0xa6, 0xc8, 0x84, 0xdb,
	0xe8, 0xa6, 0xe4, 0xa6, 0x36, 0x1f, 0x07, 0x5d, 0x28, 0x22, 0x6a, 0x1d, 0x3e, 0x09, 0xeb, 0x57,
	0x12, 0xfa, 0x50, 0xa5, 0x93, 0xa0, 0x8f, 0xe8, 0xf8, 0x2e, 0xd0, 0xab, 0xb1, 0xdd, 0x43, 0xe8,
	0x67, 0x00, 0x43, 0x3d, 0x4f, 0x1a, 0x61, 0x44, 0xf1, 0xa5, 0xa5, 0x91, 0x6b, 0xb3, 0x2e, 0x1e,
	0xa2, 0x08, 0xfc, 0x7a, 0x3c, 0xf8, 0x2f, 0x1a, 0xc0, 0xf0, 0xfb, 0x98, 0xd4, 0x79, 0xe4, 0x0b,
	0x8a, 0x55, 0x9e, 0x29, 0x27, 0x78, 0x48, 0xd6, 0x62, 0xb9, 0x67, 0xb2, 0xf6, 0xd6, 0x93, 0x77,
	0x1b, 0x3d, 0x87, 0x1f, 0x05, 0x6d, 0xa3, 0xe3, 0xf5, 0x4d, 0x9f, 0x1e, 0xb3, 0xc0, 0x94, 0x2d,
	0x4c, 0xff, 0xb8, 0x67, 0x8e, 0xbe, 0xe1, 0x9b, 0xd2, 0x6c, 0x67, 0x24, 0xf2, 0x8d, 0xdf, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x15, 0x87, 0x29, 0x32, 0xe6, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	ListUser(ctx context.Context, in *ListUserRequest, opts ...grpc.CallOption) (*UserList, error)
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*User, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*User, error)
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*User, error)
	DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	SearchUser(ctx context.Context, in *SearchUserRequest, opts ...grpc.CallOption) (*UserList, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) ListUser(ctx context.Context, in *ListUserRequest, opts ...grpc.CallOption) (*UserList, error) {
	out := new(UserList)
	err := c.cc.Invoke(ctx, "/publr.users.v1alpha2.UserService/ListUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/publr.users.v1alpha2.UserService/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/publr.users.v1alpha2.UserService/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/publr.users.v1alpha2.UserService/UpdateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/publr.users.v1alpha2.UserService/DeleteUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) SearchUser(ctx context.Context, in *SearchUserRequest, opts ...grpc.CallOption) (*UserList, error) {
	out := new(UserList)
	err := c.cc.Invoke(ctx, "/publr.users.v1alpha2.UserService/SearchUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	ListUser(context.Context, *ListUserRequest) (*UserList, error)
	CreateUser(context.Context, *CreateUserRequest) (*User, error)
	GetUser(context.Context, *GetUserRequest) (*User, error)
	UpdateUser(context.Context, *UpdateUserRequest) (*User, error)
	DeleteUser(context.Context, *DeleteUserRequest) (*empty.Empty, error)
	SearchUser(context.Context, *SearchUserRequest) (*UserList, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) ListUser(ctx context.Context, req *ListUserRequest) (*UserList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUser not implemented")
}
func (*UnimplementedUserServiceServer) CreateUser(ctx context.Context, req *CreateUserRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (*UnimplementedUserServiceServer) GetUser(ctx context.Context, req *GetUserRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (*UnimplementedUserServiceServer) UpdateUser(ctx context.Context, req *UpdateUserRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUser not implemented")
}
func (*UnimplementedUserServiceServer) DeleteUser(ctx context.Context, req *DeleteUserRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUser not implemented")
}
func (*UnimplementedUserServiceServer) SearchUser(ctx context.Context, req *SearchUserRequest) (*UserList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchUser not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_ListUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ListUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/publr.users.v1alpha2.UserService/ListUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ListUser(ctx, req.(*ListUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/publr.users.v1alpha2.UserService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/publr.users.v1alpha2.UserService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/publr.users.v1alpha2.UserService/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/publr.users.v1alpha2.UserService/DeleteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DeleteUser(ctx, req.(*DeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_SearchUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).SearchUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/publr.users.v1alpha2.UserService/SearchUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).SearchUser(ctx, req.(*SearchUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "publr.users.v1alpha2.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListUser",
			Handler:    _UserService_ListUser_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _UserService_CreateUser_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _UserService_GetUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _UserService_UpdateUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _UserService_DeleteUser_Handler,
		},
		{
			MethodName: "SearchUser",
			Handler:    _UserService_SearchUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/users/v1alpha2/users.proto",
}
