// Copyright 2019 Publr Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/prksu/publr/service/posts (interfaces: PostDatastore)

// Package mock_posts is a generated GoMock package.
package mock_posts

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	v1alpha3 "github.com/prksu/publr/pkg/api/posts/v1alpha3"
	reflect "reflect"
)

// MockPostDatastore is a mock of PostDatastore interface
type MockPostDatastore struct {
	ctrl     *gomock.Controller
	recorder *MockPostDatastoreMockRecorder
}

// MockPostDatastoreMockRecorder is the mock recorder for MockPostDatastore
type MockPostDatastoreMockRecorder struct {
	mock *MockPostDatastore
}

// NewMockPostDatastore creates a new mock instance
func NewMockPostDatastore(ctrl *gomock.Controller) *MockPostDatastore {
	mock := &MockPostDatastore{ctrl: ctrl}
	mock.recorder = &MockPostDatastoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockPostDatastore) EXPECT() *MockPostDatastoreMockRecorder {
	return m.recorder
}

// Create mocks base method
func (m *MockPostDatastore) Create(arg0 context.Context, arg1, arg2 string, arg3 *v1alpha3.Post) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create
func (mr *MockPostDatastoreMockRecorder) Create(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPostDatastore)(nil).Create), arg0, arg1, arg2, arg3)
}

// Delete mocks base method
func (m *MockPostDatastore) Delete(arg0 context.Context, arg1, arg2, arg3 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockPostDatastoreMockRecorder) Delete(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPostDatastore)(nil).Delete), arg0, arg1, arg2, arg3)
}

// Get mocks base method
func (m *MockPostDatastore) Get(arg0 context.Context, arg1, arg2, arg3 string) (*v1alpha3.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*v1alpha3.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get
func (mr *MockPostDatastoreMockRecorder) Get(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockPostDatastore)(nil).Get), arg0, arg1, arg2, arg3)
}

// List mocks base method
func (m *MockPostDatastore) List(arg0 context.Context, arg1, arg2 string, arg3, arg4 int) ([]*v1alpha3.Post, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].([]*v1alpha3.Post)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List
func (mr *MockPostDatastoreMockRecorder) List(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPostDatastore)(nil).List), arg0, arg1, arg2, arg3, arg4)
}

// Search mocks base method
func (m *MockPostDatastore) Search(arg0 context.Context, arg1 string) ([]*v1alpha3.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", arg0, arg1)
	ret0, _ := ret[0].([]*v1alpha3.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search
func (mr *MockPostDatastoreMockRecorder) Search(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockPostDatastore)(nil).Search), arg0, arg1)
}

// Update mocks base method
func (m *MockPostDatastore) Update(arg0 context.Context, arg1, arg2, arg3 string, arg4 *v1alpha3.Post) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update
func (mr *MockPostDatastoreMockRecorder) Update(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPostDatastore)(nil).Update), arg0, arg1, arg2, arg3, arg4)
}
