load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["testdata.go"],
    importpath = "github.com/prksu/publr/pkg/bindata/testdata",
    visibility = ["//visibility:public"],
)
